import { useQuery } from '@tanstack/react-query';

export interface NHLSverigeVideo {
  id: string;
  title: string;
  thumbnail: string;
  publishedAt: string;
}

// Generated by scripts/sync.mjs; missing until a sync has run with a YouTube API key
const fetchNHLSverigeVideos = async (): Promise<NHLSverigeVideo[]> => {
  const response = await fetch(`${import.meta.env.BASE_URL}data/videos.json`);
  if (!response.ok) return [];
  return response.json().catch(() => []);
};

export const useNHLSverigeVideos = () => {
  return useQuery({
    queryKey: ['nhl-sverige-videos'],
    queryFn: fetchNHLSverigeVideos,
    staleTime: 5 * 60 * 1000, // 5 minutes
    retry: 2,
  });
};
