import { useQuery } from '@tanstack/react-query';
import { Game, SwedishPlayer, SwedishGoalie, GamePoint, GoaliePerformance, PlayerGameLogEntry, CareerSeasonStats } from '@/types/nhl';
import { CURRENT_SEASON } from '@/lib/season';

// Data is generated by scripts/sync.mjs into public/data/ and served as static JSON files

interface Manifest {
  seasons: string[];
  currentSeason: string;
  lastSyncedAt: string;
}

// Rows in the data files keep the old database column names (snake_case)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DataRow = any;

const fetchData = async <T,>(file: string): Promise<T> => {
  const response = await fetch(`${import.meta.env.BASE_URL}data/${file}`);
  if (!response.ok) throw new Error(`Failed to load ${file}: ${response.status}`);
  return response.json();
};

const fetchManifest = () => fetchData<Manifest>('manifest.json');

// Rows for one season, or [] if that season has no data file
const fetchSeasonRows = async (kind: 'players' | 'goalies', season: string): Promise<DataRow[]> => {
  const { seasons } = await fetchManifest();
  return seasons.includes(season) ? fetchData<DataRow[]>(`${kind}-${season}.json`) : [];
};

// Rows for one player across all seasons, newest season first
const fetchPlayerSeasons = async (kind: 'players' | 'goalies', playerId: string): Promise<DataRow[]> => {
  const { seasons } = await fetchManifest();
  const perSeason = await Promise.all(seasons.map((season) => fetchData<DataRow[]>(`${kind}-${season}.json`)));
  return perSeason
    .flat()
    .filter((row) => row.id === playerId)
    .sort((a, b) => b.season.localeCompare(a.season));
};

// games.json is sorted newest first
const fetchGames = () => fetchData<DataRow[]>('games.json');

// Transform a data file row to the frontend type
const transformPlayer = (row: any): SwedishPlayer => ({
  id: row.id,
  name: row.name,
  team: row.team,
  teamAbbr: row.team_abbr,
  position: row.position,
  jerseyNumber: row.jersey_number,
  games: row.games,
  goals: row.goals,
  assists: row.assists,
  points: row.points,
  penaltyMinutes: row.penalty_minutes,
  plusMinus: row.plus_minus,
  timeOnIce: row.time_on_ice || '0:00',
  powerPlayGoals: row.power_play_goals,
  powerPlayPoints: row.power_play_points,
  gameWinningGoals: row.game_winning_goals,
  shots: row.shots,
  shootingPct: Number(row.shooting_pct) || 0,
  season: row.season,
});

const transformGoalie = (row: any): SwedishGoalie => ({
  id: row.id,
  name: row.name,
  team: row.team,
  teamAbbr: row.team_abbr,
  jerseyNumber: row.jersey_number,
  games: row.games,
  gamesStarted: row.games_started,
  wins: row.wins,
  losses: row.losses,
  overtimeLosses: row.overtime_losses,
  savePercentage: Number(row.save_percentage) || 0,
  goalsAgainstAverage: Number(row.goals_against_average) || 0,
  shutouts: row.shutouts,
  saves: row.saves,
  shotsAgainst: row.shots_against,
  timeOnIce: row.time_on_ice || '0:00',
  season: row.season,
});

const getOvertimeType = (period: string | null): 'OT' | 'SO' | undefined => {
  if (period === 'P4') return 'OT';
  if (period === 'P5') return 'SO';
  return undefined;
};

const transformGame = (row: any): Game => ({
  id: row.id,
  date: row.game_date,
  homeTeam: row.home_team,
  homeTeamAbbr: row.home_team_abbr,
  awayTeam: row.away_team,
  awayTeamAbbr: row.away_team_abbr,
  homeScore: row.home_score,
  awayScore: row.away_score,
  status: row.status as 'final' | 'live' | 'scheduled',
  swedishPoints: (row.swedish_points as GamePoint[]) || [],
  swedishGoalies: (row.swedish_goalies as GoaliePerformance[]) || [],
  highlightUrl: row.highlight_url,
  highlightVideoId: row.highlight_video_id || undefined,
  period: row.period,
  timeRemaining: row.time_remaining,
  overtimeType: getOvertimeType(row.period),
});

export function useSwedishPlayers(season: string = CURRENT_SEASON) {
  return useQuery({
    queryKey: ['swedish-players', season],
    queryFn: async () => {
      const rows = await fetchSeasonRows('players', season);
      return rows.map(transformPlayer).sort((a, b) => b.points - a.points);
    },
    staleTime: 1000 * 60 * 30, // 30 minutes
  });
}

export function useSwedishGoalies(season: string = CURRENT_SEASON) {
  return useQuery({
    queryKey: ['swedish-goalies', season],
    queryFn: async () => {
      const rows = await fetchSeasonRows('goalies', season);
      return rows.map(transformGoalie).sort((a, b) => b.wins - a.wins);
    },
    staleTime: 1000 * 60 * 30, // 30 minutes
  });
}

export function useNHLGames() {
  return useQuery({
    queryKey: ['nhl-games'],
    queryFn: async () => (await fetchGames()).slice(0, 20).map(transformGame),
    staleTime: 1000 * 60 * 5, // 5 minutes for games (more frequent updates)
  });
}

// Get all games from the last 7 days for Top 3 calculation
export function useRecentGamesForStats() {
  return useQuery({
    queryKey: ['recent-games-stats'],
    queryFn: async () => {
      const sevenDaysAgo = new Date();
      sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

      return (await fetchGames())
        .filter((game) => new Date(game.game_date) >= sevenDaysAgo)
        .map(transformGame);
    },
    staleTime: 1000 * 60 * 5,
  });
}

// Get a single player by ID (most recent season on record)
export function usePlayer(playerId: string) {
  return useQuery({
    queryKey: ['player', playerId],
    queryFn: async () => {
      const [latest] = await fetchPlayerSeasons('players', playerId);
      return latest ? transformPlayer(latest) : null;
    },
    enabled: !!playerId,
    staleTime: 1000 * 60 * 30,
  });
}

// Get a single goalie by ID
export function useGoalie(goalieId: string) {
  return useQuery({
    queryKey: ['goalie', goalieId],
    queryFn: async () => {
      const [latest] = await fetchPlayerSeasons('goalies', goalieId);
      return latest ? transformGoalie(latest) : null;
    },
    enabled: !!goalieId,
    staleTime: 1000 * 60 * 30,
  });
}

// Get game log for a player (games where they recorded points)
export function usePlayerGameLog(playerId: string) {
  return useQuery({
    queryKey: ['player-game-log', playerId],
    queryFn: async () => {
      const gameLog: PlayerGameLogEntry[] = [];

      for (const game of (await fetchGames()).slice(0, 50)) {
        const points = (game.swedish_points as GamePoint[]) || [];
        for (const point of points.filter(p => p.playerId === playerId)) {
          gameLog.push({
            gameId: game.id,
            gameDate: game.game_date,
            homeTeamAbbr: game.home_team_abbr,
            awayTeamAbbr: game.away_team_abbr,
            type: point.type,
            period: point.period,
            time: point.time,
            description: point.description,
          });
        }
      }

      return gameLog;
    },
    enabled: !!playerId,
    staleTime: 1000 * 60 * 5,
  });
}

// Get career stats across all seasons
export function usePlayerCareerStats(playerId: string) {
  return useQuery({
    queryKey: ['player-career', playerId],
    queryFn: async () => {
      const playerData = await fetchPlayerSeasons('players', playerId);
      if (playerData.length > 0) {
        return playerData.map((row): CareerSeasonStats => ({
          season: row.season,
          team: row.team,
          teamAbbr: row.team_abbr,
          games: row.games || 0,
          goals: row.goals || 0,
          assists: row.assists || 0,
          points: row.points || 0,
          plusMinus: row.plus_minus || 0,
          penaltyMinutes: row.penalty_minutes || 0,
        }));
      }

      const goalieData = await fetchPlayerSeasons('goalies', playerId);
      return goalieData.map((row): CareerSeasonStats => ({
        season: row.season,
        team: row.team,
        teamAbbr: row.team_abbr,
        games: row.games || 0,
        wins: row.wins || 0,
        losses: row.losses || 0,
        savePercentage: Number(row.save_percentage) || 0,
        goalsAgainstAverage: Number(row.goals_against_average) || 0,
        shutouts: row.shutouts || 0,
      }));
    },
    enabled: !!playerId,
    staleTime: 1000 * 60 * 30,
  });
}
